asttokens==2.2.1
backcall==0.2.0
decorator==5.1.1
executing==1.2.0
imageio==2.28.1
ipython==8.12.2
jedi==0.18.2
matplotlib-inline==0.1.6
networkx==3.1
numpy==1.24.3
opencv-python==4.7.0.72
packaging==23.1
pandas==2.0.1
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.5.0
prompt-toolkit==3.0.38
ptyprocess==0.7.0
pure-eval==0.2.2
Pygments==2.15.1
python-dateutil==2.8.2
pytz==2023.3
PyWavelets==1.4.1
scikit-image==0.19.3
scipy==1.10.1
six==1.16.0
stack-data==0.6.2
tifffile==2023.4.12
torch==1.7.1+cu110
torchaudio==0.7.2
torchvision==0.8.2+cu110
tqdm==4.65.0
traitlets==5.9.0
typing_extensions==4.5.0
tzdata==2023.3
wcwidth==0.2.6
